spring:
  datasource:
    url: "jdbc:h2:~/aigoya;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;"
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
