name: Build image with Jib and push to GitHub Container Registry

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: Build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and push image with Jib
        run: |
          chmod +x gradlew && ./gradlew jib
